import _HomeContainer from "./home";
import _LoginContainer from "./login";
import _PageNotFound from "./404";
import _EventDetailsContainer from "./eventDetails";
import _RegisterContainer from "./register";
import _ForgotPasswordContainer from "./forgotPassword";
import _ForgotPasswordVerifyContainer from "./forgotPassword/verify";
import _CreateEventContainer from "./createEvent";
import _ProfileContainer from "./profile";
import _MessagesContainer from "./messages";
import _SearchContainer from "./search";
import _FeedContainer from "./feeds";
import _SettingContainer from "./setting";
import _EventsContainer from "./events";
import _AdsCenterContainer from "./AdsCenter";

export const HomeContainer = _HomeContainer;
export const LoginContainer = _LoginContainer;
export const PageNotFound = _PageNotFound;
export const EventDetailsContainer = _EventDetailsContainer;
export const RegisterContainer = _RegisterContainer;
export const ForgotPasswordContainer = _ForgotPasswordContainer;
export const ForgotPasswordVerifyContainer = _ForgotPasswordVerifyContainer;
export const CreateEventContainer = _CreateEventContainer;
export const ProfileContainer = _ProfileContainer;
export const MessagesContainer = _MessagesContainer;
export const SearchContainer = _SearchContainer;
export const FeedContainer = _FeedContainer;
export const EventsContainer = _EventsContainer;
export const SettingContainer = _SettingContainer;
export const AdsCenterContainer = _AdsCenterContainer;
