import _Header from "./header";
import _Footer from "./footer";
import _Layout from "./layout";
import _Sidebar from "./sidebar";
import _Event from "./event";
import _Promotion from "./promotion";
import _UpdateProfile from "./updateProfile";
import _CreateEvent from "./createEvent";
import _Share from "./share";
import _FriendList from "./firendList";
import _MessagesCenter from "./messgesCenter";
import _ImageUploadDialoge from "./imageUploadDialoge";
import _GifUploadDialoge from "./gifUploadDialoge";
import _PostModal from "./postModal";
import _Post from "./post";
import _Group from "./singleGroup";
import _UploadAndCrop from "./uploadAndCrop";

export const Header = _Header;
export const Footer = _Footer;
export const Layout = _Layout;
export const Sidebar = _Sidebar;
export const Event = _Event;
export const Promotion = _Promotion;
export const UpdateProfile = _UpdateProfile;
export const CreateEvent = _CreateEvent;
export const Share = _Share;
export const FriendList = _FriendList;
export const MessagesCenter = _MessagesCenter;
export const ImageUploadDialoge = _ImageUploadDialoge;
export const GifUploadDialoge = _GifUploadDialoge;
export const PostModal = _PostModal;
export const Post = _Post;
export const Group = _Group;
export const UploadAndCrop = _UploadAndCrop;
