const User = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_LOGOUT: "LOGIN_LOGOUT",
  LOGIN_UPDATE: "LOGIN_UPDATE",
};

export default { User };
